# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160220_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at', '-pk')},
        ),
    ]
